### ISSUE TITLE
Panic in `debug_render_axes`

### ISSUE THREAD

**Issue by yrns** [Jondolf/avian#350]
Using `bevy_xpbd_3d = "0.4.2"`.

I consistently get a panic in debug with `PhysicsDebugPlugin` every time the player runs into a small object on the ground. It looks like the sphere being drawn via gizmo has a rotation that's not normalized:
```rust 
Direction3d::new_unchecked(self.rotation * axis)
```

I'm not sure if the rotation should be normalized here or if this is a bug in Bevy.

```
thread 'Compute Task Pool (2)' panicked at /home/al/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_math-0.13.0/src/primitives/dim3.rs:40:9:
assertion failed: value.is_normalized()
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
   3: bevy_math::primitives::dim3::Direction3d::new_unchecked
             at /home/al/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_math-0.13.0/src/primitives/dim3.rs:40:9
   4: <bevy_gizmos::gizmos::SphereBuilder<T> as core::ops::drop::Drop>::drop
             at /home/al/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_gizmos-0.13.0/src/gizmos.rs:625:21
   5: core::ptr::drop_in_place<bevy_gizmos::gizmos::SphereBuilder<bevy_xpbd_3d::plugins::debug::configuration::PhysicsGizmos>>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ptr/mod.rs:507:1
   6: bevy_xpbd_3d::plugins::debug::debug_render_axes
             at /home/al/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_xpbd_3d-0.4.2/src/plugins/debug/mod.rs:206:14
```

**Comment by kaydensigh** [comment]
I think this was a bug on the Bevy side and was fixed by https://github.com/bevyengine/bevy/commit/c75d14586999dc1ef1ff6099adbc1f0abdb46edf. Will need to wait for a Bevy release or use the source directly.

In the mean time, you can disable axis debug rendering in [PhysicsGizmos](https://docs.rs/bevy_xpbd_3d/latest/bevy_xpbd_3d/plugins/debug/struct.PhysicsGizmos.html):
```
    App::new()
...
        // Disable axis rendering https://github.com/Jondolf/bevy_xpbd/issues/350
        .insert_gizmo_group(
            PhysicsGizmos {
                axis_lengths: None,
                ..default()
            },
            GizmoConfig::default(),
        )
...
    .run();
```

**Comment by yrns** [comment]
Perfect, thanks.
